run:
  timeout: 5m
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.19'

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - gci
    - revive

linters-settings:
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/suborbital)
      - prefix(github.com/suborbital/framework-muxer-showdown)
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: warning
    enable-all-rules: false
    confidence: 0.1
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-shadowing
      - name: import-shadowing
        severity: warning
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#duplicated-imports
      - name: duplicated-imports
        severity: warning
        disabled: false
