version: "3.9"
services:
  linter:
    image: suborbital/muxer-util:latest
    volumes:
      - .:/app:rw
    working_dir: /app
    command: golangci-lint run -v ./...

  lintfixer:
    image: suborbital/muxer-util:latest
    volumes:
      - .:/app:rw
    working_dir: /app
    command: ["./ops/gci.sh"]

  mocks:
   image: suborbital/muxer-util:latest
   volumes:
      - .:/app:rw
   working_dir: /app
   command: mockery
