FROM golang:1.19

ENV GOCACHE /tmp/.cache

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install jq -y

WORKDIR /temp

RUN which jq

RUN curl -s https://api.github.com/repos/vektra/mockery/releases/latest \
    | jq '.assets | .[] | .browser_download_url | select(test(".*Linux_arm.*"))' \
    | tr -d '"' \
    | xargs -n1 curl -OL

RUN tar -xzvf *.tar.gz
RUN chmod +x mockery
RUN mv mockery /usr/local/bin/

WORKDIR /src

RUN which mockery

ENTRYPOINT ["/usr/local/bin/mockery"]
